#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].hostname=NeoBird
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm

#ln -sf /sbin/ip /usr/bin/ip

sed -i 's#downloads.openwrt.org#mirrors.cloud.tencent.com/lede#g' /etc/opkg/distfeeds.conf
sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
sed -i 's/root:::0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/openwrt_luci/ { s/snapshots/releases\/18.06.9/g; }'  /etc/opkg/distfeeds.conf

sed -i '/check_signature/d' /etc/opkg.conf

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
#echo 'iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
#echo 'iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
#echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user
#echo '[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53' >> /etc/firewall.user

#echo 'iptables -A OUTPUT -m string --string "api.installer.xiaomi.cn" --algo bm --to 65535 -j DROP' >> /etc/firewall.user

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='R24.4.4'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='NeoBird '" >> /etc/openwrt_release

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

sed -i '/255.255.255.0/a\option delegate 0' 
uci set network.lan.ifname=eth0
uci set network.lan.gateway=192.168.1.1
uci set network.lan.dns=127.0.0.1
sed -i '/option ip6assign/d' /etc/config/network
# sed -i '/option type/d' /etc/config/network #桥接
uci commit network

sed -i '/option ra_management/d' /etc/config/dhcp
sed -i '/option dhcpv6/d' /etc/config/dhcp
sed -i '/option ra/d' /etc/config/dhcp
uci set dhcp.lan.ignore=1
sed -i 's/8192/0/g' /etc/config/dhcp
sed -i '/option filter_aaaa/d' /etc/config/dhcp
sed -i '/1232/a\option filter_aaaa 1' /etc/config/dhcp
uci commit dhcp

sed -i '17,144d' /etc/config/firewall
sed -i '/option syn_flood/d' /etc/config/firewall
sed -i '15aoption masq 1' /etc/config/firewall
uci commit firewall

# wifi
uci set wireless.radio0.channel=auto
uci set wireless.@wifi-iface[0].ssid='R619AC' #设置2.4G无线的ssid 11
uci set wireless.@wifi-iface[1].ssid='R619AC-5G' #设置5G无线的ssid
uci set wireless.@wifi-iface[0].key='1925600159.' #设置无线密码 11
uci set wireless.@wifi-iface[1].key='1925600159.'  #设置5G无线密码 11

uci set wireless.@wifi-device[0].country='CN'
# uci set wireless.@wifi-device[0].disabled=0
uci set wireless.@wifi-iface[0].channel='12'
uci set wireless.@wifi-iface[0].network='lan'
uci set wireless.@wifi-iface[0].mode='ap'

uci set wireless.@wifi-iface[0].encryption='psk-mixed'
# uci set wireless.@wifi-iface[0].hidden=0

uci set wireless.@wifi-device[1].country='CN'
# uci set wireless.@wifi-device[1].disabled=0
uci set wireless.@wifi-device[1].channel='36'
uci set wireless.@wifi-iface[1].network='lan'
uci set wireless.@wifi-iface[1].mode='ap'
uci set wireless.@wifi-iface[1].encryption='psk-mixed'
uci commit wireless

sed -i 's#"IP/MAC Binding"#"地址绑定"#g' /usr/lib/lua/luci/controller/arpbind.lua
sed -i 's/"MosDNS"/"域名转发"/g' /usr/lib/lua/luci/controller/mosdns.lua
sed -i 's/"OpenClash"/"世界之窗"/g' /usr/lib/lua/luci/controller/openclash.lua
sed -i 's/"KMS Server"/"免费激活"/g' /usr/lib/lua/luci/controller/vlmcsd.lua
sed -i 's/"IPTV Helper"/"电视组播"/g' /usr/lib/lua/luci/controller/iptvhelper.lua
sed -i 's/"Argon Config"/"主题设置"/g' /usr/lib/lua/luci/controller/argon-config.lua
sed -i 's/"SmartDNS"/"域名加速"/g' /usr/lib/lua/luci/controller/smartdns.lua
sed -i 's/"UPnP"/"即插即用"/g' /usr/lib/lua/luci/controller/upnp.lua
sed -i 's/"udpxy"/"电视组播"/g' /usr/lib/lua/luci/controller/udpxy.lua
sed -i 's/"CPU Freq"/"性能优化"/g' /usr/lib/lua/luci/controller/cpufreq.lua
sed -i 's/"Turbo ACC Center"/"网络加速"/g' /usr/lib/lua/luci/controller/turboacc.lua
sed -i 's/"TTYD Terminal"/"终端命令"/g' /usr/lib/lua/luci/controller/terminal.lua
sed -i 's/"DHCP and DNS"/"动态主机"/g' /usr/lib/lua/luci/controller/admin/network.lua
sed -i 's#"Backup / Flash Firmware"#"备份恢复"#g' /usr/lib/lua/luci/controller/admin/system.lua
sed -i 's/"ShadowSocksR Plus+"/"世界之门"/g' /usr/lib/lua/luci/controller/shadowsocksr.lua
sed -i 's/"Pass Wall"/"世界之墙"/g' /usr/lib/lua/luci/controller/passwall.lua

chmod +x /etc/mosdns/*.sh
source /etc/mosdns/update.sh
source /etc/mosdns/flush_cache.sh
# echo "0 3 * * * /etc/mosdns/update.sh" >> /etc/crontabs/root
exit 0
